//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

import Foundation
import Ice
import PromiseKit

public typealias strList = [Swift.String]

public typealias byteSeq = Foundation.Data

/// Traits for Slice interface `Printer`.
public struct PrinterTraits: Ice.SliceTraits {
    public static let staticIds = ["::Demo::Printer", "::Ice::Object"]
    public static let staticId = "::Demo::Printer"
}

/// PrinterPrx overview.
///
/// PrinterPrx Methods:
///
///  - printString: 
///
///  - printStringAsync: 
///
///  - renameFile: 
///
///  - renameFileAsync: 
///
///  - deleteFile: 
///
///  - deleteFileAsync: 
///
///  - getNewIndex: 
///
///  - getNewIndexAsync: 
///
///  - findFile: 
///
///  - findFileAsync: 
///
///  - playFile: 
///
///  - playFileAsync: 
///
///  - stopFile: 
///
///  - stopFileAsync: 
///
///  - pause: 
///
///  - pauseAsync: 
///
///  - resume: 
///
///  - resumeAsync: 
///
///  - uploadPart: 
///
///  - uploadPartAsync: 
///
///  - uploadFile: 
///
///  - uploadFileAsync: 
///
///  - isPlaying: 
///
///  - isPlayingAsync: 
public protocol PrinterPrx: Ice.ObjectPrx {}

private final class PrinterPrxI: Ice.ObjectPrxI, PrinterPrx {
    public override class func ice_staticId() -> Swift.String {
        return PrinterTraits.staticId
    }
}

/// Casts a proxy to the requested type. This call contacts the server and verifies that the object
/// implements this type.
///
/// It will throw a local exception if a communication error occurs. You can optionally supply a
/// facet name and a context map.
///
/// - parameter prx: `Ice.ObjectPrx` - The proxy to be cast.
///
/// - parameter type: `PrinterPrx.Protocol` - The proxy type to cast to.
///
/// - parameter facet: `String` - The optional name of the desired facet.
///
/// - parameter context: `Ice.Context` The optional context dictionary for the remote invocation.
///
/// - returns: `PrinterPrx` - A proxy with the requested type or nil if the objet does not
///   support this type.
///
/// - throws: `Ice.LocalException` if a communication error occurs.
public func checkedCast(prx: Ice.ObjectPrx, type: PrinterPrx.Protocol, facet: Swift.String? = nil, context: Ice.Context? = nil) throws -> PrinterPrx? {
    return try PrinterPrxI.checkedCast(prx: prx, facet: facet, context: context) as PrinterPrxI?
}

/// Downcasts the given proxy to this type without contacting the remote server.
///
/// - parameter prx: `Ice.ObjectPrx` The proxy to be cast.
///
/// - parameter type: `PrinterPrx.Protocol` - The proxy type to cast to.
///
/// - parameter facet: `String` - The optional name of the desired facet
///
/// - returns: `PrinterPrx` - A proxy with the requested type
public func uncheckedCast(prx: Ice.ObjectPrx, type: PrinterPrx.Protocol, facet: Swift.String? = nil) -> PrinterPrx {
    return PrinterPrxI.uncheckedCast(prx: prx, facet: facet) as PrinterPrxI
}

/// Returns the Slice type id of the interface or class associated with this proxy type.
///
/// parameter type: `PrinterPrx.Protocol` -  The proxy type to retrieve the type id.
///
/// returns: `String` - The type id of the interface or class associated with this proxy type.
public func ice_staticId(_ type: PrinterPrx.Protocol) -> Swift.String {
    return PrinterTraits.staticId
}

/// Extension to `Ice.InputStream` class to support reading proxy of type
/// `PrinterPrx`.
public extension Ice.InputStream {
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - parameter type: `PrinterPrx.Protocol` - The type of the proxy to be extracted.
    ///
    /// - returns: `PrinterPrx?` - The extracted proxy
    func read(_ type: PrinterPrx.Protocol) throws -> PrinterPrx? {
        return try read() as PrinterPrxI?
    }
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - parameter tag: `Int32` - The numeric tag associated with the value.
    ///
    /// - parameter type: `PrinterPrx.Protocol` - The type of the proxy to be extracted.
    ///
    /// - returns: `PrinterPrx` - The extracted proxy.
    func read(tag: Swift.Int32, type: PrinterPrx.Protocol) throws -> PrinterPrx? {
        return try read(tag: tag) as PrinterPrxI?
    }
}

/// PrinterPrx overview.
///
/// PrinterPrx Methods:
///
///  - printString: 
///
///  - printStringAsync: 
///
///  - renameFile: 
///
///  - renameFileAsync: 
///
///  - deleteFile: 
///
///  - deleteFileAsync: 
///
///  - getNewIndex: 
///
///  - getNewIndexAsync: 
///
///  - findFile: 
///
///  - findFileAsync: 
///
///  - playFile: 
///
///  - playFileAsync: 
///
///  - stopFile: 
///
///  - stopFileAsync: 
///
///  - pause: 
///
///  - pauseAsync: 
///
///  - resume: 
///
///  - resumeAsync: 
///
///  - uploadPart: 
///
///  - uploadPartAsync: 
///
///  - uploadFile: 
///
///  - uploadFileAsync: 
///
///  - isPlaying: 
///
///  - isPlayingAsync: 
public extension PrinterPrx {
    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    func printString(_ iceP_s: Swift.String, context: Ice.Context? = nil) throws {
        try _impl._invoke(operation: "printString",
                          mode: .Normal,
                          write: { ostr in
                              ostr.write(iceP_s)
                          },
                          context: context)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<>` - The result of the operation
    func printStringAsync(_ iceP_s: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Void> {
        return _impl._invokeAsync(operation: "printString",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_s)
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter newName: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func renameFile(filename iceP_filename: Swift.String, newName iceP_newName: Swift.String, context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "renameFile",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_filename)
                                     ostr.write(iceP_newName)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter newName: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func renameFileAsync(filename iceP_filename: Swift.String, newName iceP_newName: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "renameFile",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_filename)
                                      ostr.write(iceP_newName)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func deleteFile(_ iceP_filename: Swift.String, context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "deleteFile",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_filename)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func deleteFileAsync(_ iceP_filename: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "deleteFile",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_filename)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Int32`
    func getNewIndex(context: Ice.Context? = nil) throws -> Swift.Int32 {
        return try _impl._invoke(operation: "getNewIndex",
                                 mode: .Normal,
                                 read: { istr in
                                     let iceP_returnValue: Swift.Int32 = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Int32>` - The result of the operation
    func getNewIndexAsync(context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Int32> {
        return _impl._invokeAsync(operation: "getNewIndex",
                                  mode: .Normal,
                                  read: { istr in
                                      let iceP_returnValue: Swift.Int32 = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `strList`
    func findFile(_ iceP_filename: Swift.String, context: Ice.Context? = nil) throws -> strList {
        return try _impl._invoke(operation: "findFile",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_filename)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: strList = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<strList>` - The result of the operation
    func findFileAsync(_ iceP_filename: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<strList> {
        return _impl._invokeAsync(operation: "findFile",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_filename)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: strList = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func playFile(_ iceP_filename: Swift.String, context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "playFile",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_filename)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter _: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func playFileAsync(_ iceP_filename: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "playFile",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_filename)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    func stopFile(context: Ice.Context? = nil) throws {
        try _impl._invoke(operation: "stopFile",
                          mode: .Normal,
                          context: context)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<>` - The result of the operation
    func stopFileAsync(context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Void> {
        return _impl._invokeAsync(operation: "stopFile",
                                  mode: .Normal,
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    func pause(context: Ice.Context? = nil) throws {
        try _impl._invoke(operation: "pause",
                          mode: .Normal,
                          context: context)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<>` - The result of the operation
    func pauseAsync(context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Void> {
        return _impl._invokeAsync(operation: "pause",
                                  mode: .Normal,
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    func resume(context: Ice.Context? = nil) throws {
        try _impl._invoke(operation: "resume",
                          mode: .Normal,
                          context: context)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<>` - The result of the operation
    func resumeAsync(context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Void> {
        return _impl._invokeAsync(operation: "resume",
                                  mode: .Normal,
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter part: `byteSeq`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func uploadPart(id iceP_id: Swift.Int32, part iceP_part: byteSeq, context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "uploadPart",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_id)
                                     ostr.write(iceP_part)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter part: `byteSeq`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func uploadPartAsync(id iceP_id: Swift.Int32, part iceP_part: byteSeq, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "uploadPart",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_id)
                                      ostr.write(iceP_part)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func uploadFile(id iceP_id: Swift.Int32, filename iceP_filename: Swift.String, context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "uploadFile",
                                 mode: .Normal,
                                 write: { ostr in
                                     ostr.write(iceP_id)
                                     ostr.write(iceP_filename)
                                 },
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func uploadFileAsync(id iceP_id: Swift.Int32, filename iceP_filename: Swift.String, context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "uploadFile",
                                  mode: .Normal,
                                  write: { ostr in
                                      ostr.write(iceP_id)
                                      ostr.write(iceP_filename)
                                  },
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - returns: `Swift.Bool`
    func isPlaying(context: Ice.Context? = nil) throws -> Swift.Bool {
        return try _impl._invoke(operation: "isPlaying",
                                 mode: .Normal,
                                 read: { istr in
                                     let iceP_returnValue: Swift.Bool = try istr.read()
                                     return iceP_returnValue
                                 },
                                 context: context)
    }

    ///
    /// - parameter context: `Ice.Context` - Optional request context.
    ///
    /// - parameter sentOn: `Dispatch.DispatchQueue?` - Optional dispatch queue used to
    ///   dispatch the sent callback.
    ///
    /// - parameter sentFlags: `Dispatch.DispatchWorkItemFlags?` - Optional dispatch flags used
    ///   to dispatch the sent callback
    ///
    /// - parameter sent: `((Swift.Bool) -> Swift.Void)` - Optional sent callback.
    ///
    /// - returns: `PromiseKit.Promise<Swift.Bool>` - The result of the operation
    func isPlayingAsync(context: Ice.Context? = nil, sentOn: Dispatch.DispatchQueue? = nil, sentFlags: Dispatch.DispatchWorkItemFlags? = nil, sent: ((Swift.Bool) -> Swift.Void)? = nil) -> PromiseKit.Promise<Swift.Bool> {
        return _impl._invokeAsync(operation: "isPlaying",
                                  mode: .Normal,
                                  read: { istr in
                                      let iceP_returnValue: Swift.Bool = try istr.read()
                                      return iceP_returnValue
                                  },
                                  context: context,
                                  sentOn: sentOn,
                                  sentFlags: sentFlags,
                                  sent: sent)
    }
}


/// Dispatcher for `Printer` servants.
public struct PrinterDisp: Ice.Disp {
    public let servant: Printer
    private static let defaultObject = Ice.ObjectI<PrinterTraits>()

    public init(_ servant: Printer) {
        self.servant = servant
    }

    public func dispatch(request: Ice.Request, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        request.startOver()
        switch current.operation {
        case "deleteFile":
            return try servant._iceD_deleteFile(incoming: request, current: current)
        case "findFile":
            return try servant._iceD_findFile(incoming: request, current: current)
        case "getNewIndex":
            return try servant._iceD_getNewIndex(incoming: request, current: current)
        case "ice_id":
            return try (servant as? Object ?? PrinterDisp.defaultObject)._iceD_ice_id(incoming: request, current: current)
        case "ice_ids":
            return try (servant as? Object ?? PrinterDisp.defaultObject)._iceD_ice_ids(incoming: request, current: current)
        case "ice_isA":
            return try (servant as? Object ?? PrinterDisp.defaultObject)._iceD_ice_isA(incoming: request, current: current)
        case "ice_ping":
            return try (servant as? Object ?? PrinterDisp.defaultObject)._iceD_ice_ping(incoming: request, current: current)
        case "isPlaying":
            return try servant._iceD_isPlaying(incoming: request, current: current)
        case "pause":
            return try servant._iceD_pause(incoming: request, current: current)
        case "playFile":
            return try servant._iceD_playFile(incoming: request, current: current)
        case "printString":
            return try servant._iceD_printString(incoming: request, current: current)
        case "renameFile":
            return try servant._iceD_renameFile(incoming: request, current: current)
        case "resume":
            return try servant._iceD_resume(incoming: request, current: current)
        case "stopFile":
            return try servant._iceD_stopFile(incoming: request, current: current)
        case "uploadFile":
            return try servant._iceD_uploadFile(incoming: request, current: current)
        case "uploadPart":
            return try servant._iceD_uploadPart(incoming: request, current: current)
        default:
            throw Ice.OperationNotExistException(id: current.id, facet: current.facet, operation: current.operation)
        }
    }
}

public protocol Printer {
    ///
    /// - parameter s: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    func printString(s: Swift.String, current: Ice.Current) throws

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter newName: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func renameFile(filename: Swift.String, newName: Swift.String, current: Ice.Current) throws -> Swift.Bool

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func deleteFile(filename: Swift.String, current: Ice.Current) throws -> Swift.Bool

    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Int32`
    func getNewIndex(current: Ice.Current) throws -> Swift.Int32

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `strList`
    func findFile(filename: Swift.String, current: Ice.Current) throws -> strList

    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func playFile(filename: Swift.String, current: Ice.Current) throws -> Swift.Bool

    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    func stopFile(current: Ice.Current) throws

    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    func pause(current: Ice.Current) throws

    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    func resume(current: Ice.Current) throws

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter part: `byteSeq`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func uploadPart(id: Swift.Int32, part: byteSeq, current: Ice.Current) throws -> Swift.Bool

    ///
    /// - parameter id: `Swift.Int32`
    ///
    /// - parameter filename: `Swift.String`
    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func uploadFile(id: Swift.Int32, filename: Swift.String, current: Ice.Current) throws -> Swift.Bool

    ///
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// - returns: `Swift.Bool`
    func isPlaying(current: Ice.Current) throws -> Swift.Bool
}

/// Printer overview.
///
/// Printer Methods:
///
///  - printString: 
///
///  - renameFile: 
///
///  - deleteFile: 
///
///  - getNewIndex: 
///
///  - findFile: 
///
///  - playFile: 
///
///  - stopFile: 
///
///  - pause: 
///
///  - resume: 
///
///  - uploadPart: 
///
///  - uploadFile: 
///
///  - isPlaying: 
public extension Printer {
    func _iceD_printString(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let iceP_s: Swift.String = try inS.read { istr in
            let iceP_s: Swift.String = try istr.read()
            return iceP_s
        }

        try self.printString(s: iceP_s, current: current)

        return inS.setResult()
    }

    func _iceD_renameFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let (iceP_filename, iceP_newName): (Swift.String, Swift.String) = try inS.read { istr in
            let iceP_filename: Swift.String = try istr.read()
            let iceP_newName: Swift.String = try istr.read()
            return (iceP_filename, iceP_newName)
        }

        let iceP_returnValue = try self.renameFile(filename: iceP_filename, newName: iceP_newName, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_deleteFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let iceP_filename: Swift.String = try inS.read { istr in
            let iceP_filename: Swift.String = try istr.read()
            return iceP_filename
        }

        let iceP_returnValue = try self.deleteFile(filename: iceP_filename, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_getNewIndex(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        try inS.readEmptyParams()

        let iceP_returnValue = try self.getNewIndex(current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_findFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let iceP_filename: Swift.String = try inS.read { istr in
            let iceP_filename: Swift.String = try istr.read()
            return iceP_filename
        }

        let iceP_returnValue = try self.findFile(filename: iceP_filename, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_playFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let iceP_filename: Swift.String = try inS.read { istr in
            let iceP_filename: Swift.String = try istr.read()
            return iceP_filename
        }

        let iceP_returnValue = try self.playFile(filename: iceP_filename, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_stopFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        try inS.readEmptyParams()

        try self.stopFile(current: current)

        return inS.setResult()
    }

    func _iceD_pause(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        try inS.readEmptyParams()

        try self.pause(current: current)

        return inS.setResult()
    }

    func _iceD_resume(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        try inS.readEmptyParams()

        try self.resume(current: current)

        return inS.setResult()
    }

    func _iceD_uploadPart(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let (iceP_id, iceP_part): (Swift.Int32, byteSeq) = try inS.read { istr in
            let iceP_id: Swift.Int32 = try istr.read()
            let iceP_part: byteSeq = try istr.read()
            return (iceP_id, iceP_part)
        }

        let iceP_returnValue = try self.uploadPart(id: iceP_id, part: iceP_part, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_uploadFile(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        let (iceP_id, iceP_filename): (Swift.Int32, Swift.String) = try inS.read { istr in
            let iceP_id: Swift.Int32 = try istr.read()
            let iceP_filename: Swift.String = try istr.read()
            return (iceP_id, iceP_filename)
        }

        let iceP_returnValue = try self.uploadFile(id: iceP_id, filename: iceP_filename, current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }

    func _iceD_isPlaying(incoming inS: Ice.Incoming, current: Ice.Current) throws -> PromiseKit.Promise<Ice.OutputStream>? {
        try inS.readEmptyParams()

        let iceP_returnValue = try self.isPlaying(current: current)

        return inS.setResult{ ostr in
            ostr.write(iceP_returnValue)
        }
    }
}
